# Generated by Django 3.2.12 on 2024-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_address_user_avatar_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/profile.jpeg', null=True, upload_to='images'),
        ),
    ]
